baseURL = 'https://data-dancers.github.io/'
languageCode = 'en-us'
title = 'Data Dancers'
theme = 'ananke'

resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[menus]
  [[menus.main]]
    name = "Discord"
    weight = 5
    identifier = "discord"
    url = "https://discord.gg/xs5ztf6THf"

# All menu items defined this way will link externally -> new tab

[params]
  text_color = "near-white"
  author = ""
  favicon = "/images/favicon.ico"
  site_logo = ""
  description = "Atlanta Livecoders"
  background_color_class = "bg-transparent"
  recent_posts_number = 3

[markup.goldmark.renderer]
  # TODO TEMP
  unsafe = true # Allow HTML in md files
